# fly.toml app configuration file generated for zoltan-antal-bloglist-sql on 2024-01-15T13:03:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zoltan-antal-bloglist-sql"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
