# fly.toml app configuration file generated for zoltan-antal-phonebook on 2023-10-23T10:15:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "zoltan-antal-phonebook"
primary_region = "lhr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
